using System;

public enum GUI_FSM_EVENT
{
    [GUIFsmEvent("MTD-GUI/GUI_DESERIALIZATION")]
    ON_GUI_DESERIALIZATION = 5,
    [GUIFsmEvent("MTD-GUI/GUI_INITIALIZE")]
    ON_GUI_INITIALIZE = 0,
    [GUIFsmEvent("MTD-GUI/GUI_PREPARE_ANIMATE")]
    ON_GUI_PREPARE_ANIMATE = 2,
    [GUIFsmEvent("MTD-GUI/GUI_RELEASE")]
    ON_GUI_RELEASE = 1,
    [GUIFsmEvent("MTD-GUI/GUI_RESET")]
    ON_GUI_RESET = 3,
    [GUIFsmEvent("MTD-GUI/GUI_SERIALIZATION")]
    ON_GUI_SERIALIZATION = 4
}

